# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 622b773077e226dd8aae2baaacb4807cb5412b61e2d6bfcb4369c59d5416520878bbd38a70f8cdf4c0554b433fe331a3be71e629023d0907c00958e6253d2bbe

test:
  secret_key_base: bbed912e6511bcaee056aee33d50e8d2770bc9919cea10837706b97a2cf34b6d1b03540650b28483448826f76f618e963d7dd5c01bbd1adeb134d3fe6df21014

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
